DROP TABLE ACCOUNTS;
DROP TABLE ACCOUNTS_TYPES;

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID int NOT NULL UNIQUE AUTO_INCREMENT,
    ACCOUNT_NAME varchar(40),
    ACCOUNT_NUMBER varchar(40),
    BALANCE int,
    INTEREST int, 
    LAST_STATEMENT_DATE Date,
    PAYMENT_DATE Date,
    ACCOUNT_TYPE_ID Integer,
    PRIMARY KEY(ACCOUNT_ID)
);

INSERT INTO ACCOUNTS (ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, INTEREST, LAST_STATEMENT_DATE, PAYMENT_DATE, ACCOUNT_TYPE_ID) VALUES ('ONETestAccount', '12345', 9800, 5, '2020-05-28', '2020-05-28', 1);
INSERT INTO ACCOUNTS (ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, INTEREST, LAST_STATEMENT_DATE, PAYMENT_DATE, ACCOUNT_TYPE_ID) VALUES ('TWOTestAccount', '678910', 1200, 3, '2020-05-28', '2020-05-28',2);
INSERT INTO ACCOUNTS (ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, INTEREST, LAST_STATEMENT_DATE, PAYMENT_DATE, ACCOUNT_TYPE_ID) VALUES ('THREETestAccount', '11121314', 3800, 4, '2020-05-28', '2020-05-28',3);
INSERT INTO ACCOUNTS (ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, INTEREST, LAST_STATEMENT_DATE, PAYMENT_DATE, ACCOUNT_TYPE_ID) VALUES ('FOURTestAccount', '15161718', 4700, 2, '2020-05-28', '2020-05-28',4);
INSERT INTO ACCOUNTS (ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, INTEREST, LAST_STATEMENT_DATE, PAYMENT_DATE, ACCOUNT_TYPE_ID) VALUES ('FIVETestAccount', '19202122', 5900, 5, '2020-05-28', '2020-05-28',5);


CREATE TABLE IF NOT EXISTS ACCOUNTS_TYPES (
    ACCOUNT_TYPE_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    INVESTING BOOLEAN,
    SAVINGS BOOLEAN,
    PRIMARY KEY(ACCOUNT_TYPE_ID)
);

INSERT INTO ACCOUNTS_TYPES (INVESTING,SAVINGS) VALUES (true, null);
INSERT INTO ACCOUNTS_TYPES (INVESTING,SAVINGS) VALUES (null,true);
INSERT INTO ACCOUNTS_TYPES (INVESTING,SAVINGS) VALUES (true, null);
INSERT INTO ACCOUNTS_TYPES (INVESTING,SAVINGS) VALUES (true, null);
INSERT INTO ACCOUNTS_TYPES (INVESTING,SAVINGS) VALUES (null, false);
