CREATE TABLE IF NOT EXISTS test_tbl_transactions(
  TRANSACTION_ID int,
  TRANSACTION_TYPE int,
  TRANSACTION_DATE DATETIME,
  description VARCHAR(160),
  amount DOUBLE,
  ACCOUNT_FROM_ID int,
  ACCOUNT_TO_ID int
);

INSERT INTO test_tbl_transactions(TRANSACTION_ID, TRANSACTION_TYPE, TRANSACTION_DATE, description, amount, ACCOUNT_FROM_ID, ACCOUNT_TO_ID) VALUES (1, 1, '2022-07-13 00:00:00', 'Amazon Purchase', 100.00, 1, 2);
INSERT INTO test_tbl_transactions(TRANSACTION_ID, TRANSACTION_TYPE, TRANSACTION_DATE, description, amount, ACCOUNT_FROM_ID, ACCOUNT_TO_ID) VALUES (2, 1, '2022-07-13 00:00:00', 'Amazon Purchase', 100.00, 3, 4);
INSERT INTO test_tbl_transactions(TRANSACTION_ID, TRANSACTION_TYPE, TRANSACTION_DATE, description, amount, ACCOUNT_FROM_ID, ACCOUNT_TO_ID) VALUES (3, 1, '2022-07-13 00:00:00', 'Amazon Purchase', 100.00, 5, 6);